import os
import uuid
from app.core.config import settings

ALLOWED_EXTENSIONS = {".pdf", ".docx"}
MAX_FILE_SIZE_BYTES = 20 * 1024 * 1024  # 20 MB

class FileStorageService:
    def __init__(self):
        os.makedirs(settings.UPLOAD_DIR, exist_ok=True)

    def save_file(self, file_content: bytes, filename: str) -> str:
        """
        Saves file content to UPLOAD_DIR.
        Generates a UUID-based storage name; the original filename is
        sanitized (path stripped) and kept only for display purposes.
        """
        # Strip any directory components the client may have sent
        safe_original_name = os.path.basename(filename)
        ext = os.path.splitext(safe_original_name)[1].lower()

        if ext not in ALLOWED_EXTENSIONS:
            raise ValueError(f"Unsupported file type: {ext}")

        # Storage filename is FULLY generated by us — never derived from client input
        unique_filename = f"{uuid.uuid4()}{ext}"
        file_path = os.path.join(settings.UPLOAD_DIR, unique_filename)

        with open(file_path, "wb") as f:
            f.write(file_content)

        return file_path

    def get_file_content(self, file_path: str) -> bytes:
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")
        with open(file_path, "rb") as f:
            return f.read()

    def delete_file(self, file_path: str) -> bool:
        if os.path.exists(file_path):
            os.remove(file_path)
            return True
        return False

file_storage = FileStorageService()